include(${CMAKE_CURRENT_LIST_DIR}/common.cmake)

set_compiler_flags("SNOW")

# Default type is BOOL. Must specify type for non-yet-existent cached variables.
# This could be much better if normal variables worked like -D
setc(DISABLE_SHARED OFF)
setc(ENABLED_PROFILING OFF)
setc(ENABLE_DTRACE OFF)
setc(MAX_INDEXES 128 STRING)
setc(MUTEXTYPE futex STRING)
setc(SECURITY_HARDENED OFF)
setc(MYSQL_MAINTAINER_MODE NO STRING)
setc(CONC_WITH_DYNCOL NO)
setc(CONC_WITH_EXTERNAL_ZLIB NO)
setc(CONC_WITH_MYSQLCOMPAT NO)
setc(CONC_WITH_UNIT_TESTS NO)
setc(GSSAPI_FOUND FALSE)
setc(UPDATE_SUBMODULES OFF)
setc(USE_ARIA_FOR_TMP_TABLES OFF)
setc(WITH_DBUG_TRACE OFF)
setc(WITH_WSREP OFF)
setc(WITH_NUMA OFF STRING)
setc(WITH_SAFEMALLOC OFF)
setc(WITH_UNIT_TESTS OFF)

set(plugins_to_exclude
  PLUGIN_CONNECT
  PLUGIN_OQGRAPH
  PLUGIN_MROONGA
  PLUGIN_TOKUDB
  PLUGIN_SPIDER
  PLUGIN_SPHINX
  PLUGIN_ROCKSDB
  PLUGIN_SEMISYNC_MASTER
  PLUGIN_SEMISYNC_SLAVE
  PLUGIN_AUDIT_NULL
  PLUGIN_AUTH_0X0100
  PLUGIN_AUTH_TEST_PLUGIN
  PLUGIN_BLACKHOLE
  PLUGIN_DAEMON_EXAMPLE
  PLUGIN_DEBUG_KEY_MANAGEMENT
  PLUGIN_DIALOG_EXAMPLES
  PLUGIN_DISKS
  PLUGIN_EXAMPLE
  PLUGIN_EXAMPLE_KEY_MANAGEMENT
  PLUGIN_FEDERATED
  PLUGIN_FEDERATEDX
  PLUGIN_FEEDBACK
  PLUGIN_FTEXAMPLE
  PLUGIN_QA_AUTH_CLIENT
  PLUGIN_QA_AUTH_INTERFACE
  PLUGIN_QA_AUTH_SERVER
  PLUGIN_TEST_SQL_DISCOVERY
  PLUGIN_TEST_VERSIONING
)

exclude_plugins(${plugins_to_exclude})
make_plugins_static_if_shared_libs_are_disabled()